spring.application.name=Backend

# Conexión a PostgreSQL en la nube (Neon) usando variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de Hibernate (Mantiene los datos seguros con 'update')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Clave secreta para firmar los JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
